---
- hosts: localhost
  vars_files: ./vars.yaml

  tasks: 
    - name: Create Lab VM - ESXi
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: 'false'
        datacenter: '{{datacenter_name}}'
        folder: '{{ folder_prefix + student_ID }}'
        name: '{{ item.vmname }}'
        state: poweredoff
        guest_id: '{{ item.guest_id }}'
        esxi_hostname: "{{ esxi_hostname }}"
        hardware:
          version: 20
          num_cpus: '{{ item.cpus }}'
          nested_virt: '{{ item.nested }}'
          memory_mb: '{{ item.memory }}'
          scsi: paravirtual
        disk:
        - size_gb: 200
          controller_type: 'paravirtual'
          controller_number: 0
          unit_number: 0
          type: thin
          datastore: '{{ datastore_name }}'
        - size_gb: 50
          controller_type: 'nvme'
          controller_number: 0
          unit_number: 0
          type: thin
          datastore: '{{ datastore_name }}'
        - size_gb: 50
          controller_type: 'nvme'
          controller_number: 0
          unit_number: 1
          type: thin
          datastore: '{{ datastore_name }}'
        - size_gb: 200
          controller_type: 'nvme'
          controller_number: 0
          unit_number: 2
          type: thin
          datastore: '{{ datastore_name }}'
        - size_gb: 200
          controller_type: 'nvme'
          controller_number: 0
          unit_number: 3
          type: thin
          datastore: '{{ datastore_name }}'
        networks:
        - name: '{{ private_net }}'
          device_type: vmxnet3
        - name: '{{ private_net }}'
          device_type: vmxnet3
        - name: '{{ private_net }}'
          device_type: vmxnet3
        - name: '{{ private_net }}'
          device_type: vmxnet3
        cdrom:
        - controller_number: 0
          unit_number: 0
          state: present
          type: iso
          iso_path: '{{ item.iso_filename }}'
      loop:
      - { vmname: "{{ student_ID + '-ESXi-01'}}", guest_id: vmkernel8Guest, cpus: 4, nested: true, memory: 16384,  iso_filename : "{{ iso_folder + 'VMware-VMvisor-Installer-8.0U2b-23305546.x86_64.iso' }}" }
      - { vmname: "{{ student_ID + '-ESXi-02'}}", guest_id: vmkernel8Guest, cpus: 4, nested: true, memory: 16384,  iso_filename : "{{ iso_folder + 'VMware-VMvisor-Installer-8.0U2b-23305546.x86_64.iso' }}" }
      - { vmname: "{{ student_ID + '-ESXi-03'}}", guest_id: vmkernel8Guest, cpus: 4, nested: true, memory: 16384,  iso_filename : "{{ iso_folder + 'VMware-VMvisor-Installer-8.0U2b-23305546.x86_64.iso' }}" }
      - { vmname: "{{ student_ID + '-ESXi-04'}}", guest_id: vmkernel8Guest, cpus: 4, nested: true, memory: 16384,  iso_filename : "{{ iso_folder + 'VMware-VMvisor-Installer-8.0U2b-23305546.x86_64.iso' }}" }
      delegate_to: localhost
      register: deploy_vm


    - name: Create Lab VM - Storage
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: 'false'
        datacenter: '{{datacenter_name}}'
        folder: '{{ folder_prefix + student_ID }}'
        name: '{{ item.vmname }}'
        state: poweredoff
        guest_id: '{{ item.guest_id }}'
        esxi_hostname: "{{ esxi_hostname }}"
        hardware:
          version: 20
          num_cpus: '{{ item.cpus }}'
          nested_virt: '{{ item.nested }}'
          memory_mb: '{{ item.memory }}'
          scsi: paravirtual
        disk:
        - size_gb: 40
          controller_type: 'paravirtual'
          controller_number: 0
          unit_number: 0
          type: thin
          datastore: '{{ datastore_name }}'
        - size_gb: 100
          controller_type: 'paravirtual'
          controller_number: 0
          unit_number: 1
          type: thin
          datastore: '{{ datastore_name }}'
        - size_gb: 100
          controller_type: 'paravirtual'
          controller_number: 0
          unit_number: 2
          type: thin
          datastore: '{{ datastore_name }}'
        - size_gb: 100
          controller_type: 'paravirtual'
          controller_number: 0
          unit_number: 3
          type: thin
          datastore: '{{ datastore_name }}'
        - size_gb: 100
          controller_type: 'paravirtual'
          controller_number: 0
          unit_number: 4
          type: thin
          datastore: '{{ datastore_name }}'          
        networks:
        - name: "{{ student_ID + '-Storage' }}"
          device_type: vmxnet3
        cdrom:
        - controller_number: 0
          unit_number: 0
          state: present
          type: iso
          iso_path: '{{ item.iso_filename }}'
      loop:
      - { vmname: "{{ student_ID + '-Storage'}}", guest_id: freebsd13_64Guest, cpus: 4, nested: false, memory: 8192,  iso_filename : "{{ iso_folder + 'TrueNAS-13.0-U6.1.iso' }}" }
      delegate_to: localhost
      register: deploy_vm      
