---
- hosts: localhost
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "vcsa.vclass.reca6"
    vcenter_username: "administrator@vsphere.reca6"
    vcenter_password: "VMware1!"
    datacenter_name: "RECA6"

  tasks: 
    - name: Create a Students folder
      community.vmware.vcenter_folder:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        datacenter: '{{ datacenter_name }}'
        folder_name: '{{ item }}'
        parent_folder: "3.Students"
        state: present
      register: sub_folder_creation_result
      loop:
        - S00
        - S01
        - S02
        - S03
        - S04
        - S05
        - S06
        - S07
        - S08
        - S09
        - S10
        - S11
        - S12
        - S13
        - S14
        - S15
      delegate_to: localhost
